[package]
name = "connect4"
version = "0.1.0"
authors = ["Sebastian Stein <seb.kde@hpfsc.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
